
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Celinda Recinos
 */



public class JFPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form JFPrincipal
     */
    
    
    public JFPrincipal() {
        
     
    
        initComponents();
       
    }
    
   
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnAbriArchivoR = new javax.swing.JButton();
        BtnAbrirArchivoA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BtnComprobar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaReglas = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtAreaEstados = new javax.swing.JTextArea();
        BtnAbriArchivoE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtAreaAlfabeto = new javax.swing.JTextArea();
        TxtCadena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agregar reglas:");

        jLabel2.setText("Cadena:");

        BtnAbriArchivoR.setText("Abrir Archivo");
        BtnAbriArchivoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbriArchivoRActionPerformed(evt);
            }
        });

        BtnAbrirArchivoA.setText("Abrir Archivo");
        BtnAbrirArchivoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirArchivoAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ANALIZADOR LÉXICO");

        BtnComprobar.setText("Comprobar cadena");
        BtnComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprobarActionPerformed(evt);
            }
        });

        TxtAreaReglas.setColumns(20);
        TxtAreaReglas.setRows(5);
        jScrollPane1.setViewportView(TxtAreaReglas);

        TxtAreaEstados.setColumns(20);
        TxtAreaEstados.setRows(5);
        jScrollPane3.setViewportView(TxtAreaEstados);

        BtnAbriArchivoE.setText("Abrir Archivo");
        BtnAbriArchivoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbriArchivoEActionPerformed(evt);
            }
        });

        jLabel4.setText("Agregar estados:");

        jLabel5.setText("Agregar alfabeto:");

        TxtAreaAlfabeto.setColumns(20);
        TxtAreaAlfabeto.setRows(5);
        jScrollPane4.setViewportView(TxtAreaAlfabeto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(TxtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BtnComprobar)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAbriArchivoR))
                    .addComponent(jScrollPane1))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAbriArchivoE))
                            .addComponent(jScrollPane3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(BtnAbrirArchivoA))
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BtnAbrirArchivoA))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BtnAbriArchivoR)
                            .addComponent(jLabel4)
                            .addComponent(BtnAbriArchivoE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BtnComprobar)
                    .addComponent(TxtCadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void BtnAbriArchivoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbriArchivoRActionPerformed
        
        
  String aux="";   
  TxtAreaReglas.setText("");
  try
  {
   /**llamamos el metodo que permite cargar la ventana*/
   JFileChooser file=new JFileChooser();
   file.showOpenDialog(this);
   /**abrimos el archivo seleccionado*/
   File abre=file.getSelectedFile();
 
   /**recorremos el archivo, lo leemos para plasmarlo
   *en el area de texto*/
   if(abre!=null)
   {     
      FileReader archivos=new FileReader(abre);
      BufferedReader lee=new BufferedReader(archivos);
      while((aux=lee.readLine())!=null)
      {
         TxtAreaReglas.append(aux+"\n");
      }
         lee.close();
    }    
   }
   catch(IOException ex)
   {
     JOptionPane.showMessageDialog(null,ex+"" +
           "\nNo se ha encontrado el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
    }
  
        
    }//GEN-LAST:event_BtnAbriArchivoRActionPerformed

    private void BtnAbrirArchivoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirArchivoAActionPerformed
        // TODO add your handling code here:
        String aux="";   
  TxtAreaAlfabeto.setText("");
  try
  {
   /**llamamos el metodo que permite cargar la ventana*/
   JFileChooser file=new JFileChooser();
   file.showOpenDialog(this);
   /**abrimos el archivo seleccionado*/
   File abre=file.getSelectedFile();
 
   /**recorremos el archivo, lo leemos para plasmarlo
   *en el area de texto*/
   if(abre!=null)
   {     
      FileReader archivos=new FileReader(abre);
      BufferedReader lee=new BufferedReader(archivos);
      while((aux=lee.readLine())!=null)
      {
         TxtAreaAlfabeto.append(aux+"\n");
      }
         lee.close();
    }    
   }
   catch(IOException ex)
   {
     JOptionPane.showMessageDialog(null,ex+"" +
           "\nNo se ha encontrado el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
    }
  
        
    
    }//GEN-LAST:event_BtnAbrirArchivoAActionPerformed

    private void BtnComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprobarActionPerformed
    StringTokenizer st1 = new StringTokenizer(TxtAreaEstados.getText(),",");
    String[] estados = new String[st1.countTokens()];
    
    int i=0;
       while(st1.hasMoreTokens())
       {
           String linea = st1.nextToken();
           //TxtAreaComprobar.append("\n"+linea);
           estados[i] = linea;
           System.out.println(estados[i]);
           i++;
       }
    
    StringTokenizer st2 = new StringTokenizer(TxtAreaAlfabeto.getText(),",");
    String[] alfabeto = new String[st2.countTokens()]; 
    
    i=0;
       while(st2.hasMoreTokens())
       {
           String linea = st2.nextToken();
           //TxtAreaComprobar.append("\n"+linea);
           alfabeto[i] = linea;
           System.out.println(alfabeto[i]);
           i++;
       }
    
    StringTokenizer st3 = new StringTokenizer(TxtAreaReglas.getText(),";");
    String[] reglas = new String[st3.countTokens()];
        
    i=0;
       while(st3.hasMoreTokens())
       {
           String linea = st3.nextToken();
           //TxtAreaComprobar.append("\n"+linea);
           reglas[i] = linea;
           System.out.println(reglas[i]);
           i++;
       }    
        
        
        char[] cadena= new char[TxtCadena.getText().length()];
        cadena= TxtCadena.getText().toCharArray();
        
        i=0;
        while(i<cadena.length)
        {
            System.out.println(cadena[i]);
            i++;
        }
       
       int contEncontrado=0;
       int contNOEncontrado=0;
       int j=0;
       int k=0;
       int cont=0;
       boolean encontro= false;
       
       while(j<=cadena.length-1)
       {
       for(i=0;i<=alfabeto.length-2;i++)
       {
           if(alfabeto[i].charAt(0)==cadena[j])
           {
               JOptionPane.showMessageDialog(this, "El caracter #"+(j+1)+" de la cadena SI se encuentra en el legunaje, en el simbolo #"+(i+1));
               contEncontrado++;
               
               
               
               if(reglas[k].charAt(0)==cadena[j]||reglas[k].charAt(3)==cadena[j])
               {
                   
                   JOptionPane.showMessageDialog(this, "El caracter #"+(j+1)+" de la cadena SI se encuentra en el estado #"+k);
                   
                   if (reglas[k].charAt(0)==cadena[j]&&reglas[k].charAt(1)=='F' || reglas[k].charAt(0)==cadena[j]&&reglas[k].charAt(4)=='F') {
                       JOptionPane.showMessageDialog(this, "La Cadena llego a su estado final, PERTENECE AL AUTOMATA");
                       //j=cadena.length-1;
                       encontro = true;
                       
                   }
                   else if (reglas[k].charAt(0)=='*' && reglas[k].charAt(1)=='F' || reglas[k].charAt(3)=='*'&& reglas[k].charAt(4)== 'F') {
                       JOptionPane.showMessageDialog(this, "La Cadena llego a su estado final, PERTENECE AL AUTOMATA");
                       //j=cadena.length-1;
                       encontro = true;
                   }
                   
                   
                   else if(reglas[k].charAt(0)==cadena[j]){
                       k=Integer.parseInt(String.valueOf(reglas[k].charAt(1)));
                       System.out.println(k);
                   }
                   else if(reglas[k].charAt(3)==cadena[j]){
                       k=Integer.parseInt(String.valueOf(reglas[k].charAt(4)));
                       System.out.println(k);
                   }
                   
               }
               
               else
               
               JOptionPane.showMessageDialog(this, "El caracter #"+(j+1)+" de la cadena NO se encuentra en el estado #"+k);
           }
           else
           JOptionPane.showMessageDialog(this, "El caracter #"+(j+1)+" de la cadena NO se encuentra en el legunaje, en el simbolo #"+(i+1));
           
       }
       
       
       j++;
       
       
       }
       if(encontro==false) JOptionPane.showMessageDialog(this, "La Cadena ingresada NO llega a un estado final Ó no se encuentra dentro del alfabeto, NO PERTENECE AL AUTOMATA");
           
       
       //}
       
    }//GEN-LAST:event_BtnComprobarActionPerformed

    private void BtnAbriArchivoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbriArchivoEActionPerformed
        
        String aux="";   
  TxtAreaEstados.setText("");
  try
  {
   /**llamamos el metodo que permite cargar la ventana*/
   JFileChooser file=new JFileChooser();
   file.showOpenDialog(this);
   /**abrimos el archivo seleccionado*/
   File abre=file.getSelectedFile();
 
   /**recorremos el archivo, lo leemos para plasmarlo
   *en el area de texto*/
   if(abre!=null)
   {     
      FileReader archivos=new FileReader(abre);
      BufferedReader lee=new BufferedReader(archivos);
      while((aux=lee.readLine())!=null)
      {
         TxtAreaEstados.append(aux+"\n");
      }
         lee.close();
    }    
   }
   catch(IOException ex)
   {
     JOptionPane.showMessageDialog(null,ex+"" +
           "\nNo se ha encontrado el archivo",
                 "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_BtnAbriArchivoEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbriArchivoE;
    private javax.swing.JButton BtnAbriArchivoR;
    private javax.swing.JButton BtnAbrirArchivoA;
    private javax.swing.JButton BtnComprobar;
    public static javax.swing.JTextArea TxtAreaAlfabeto;
    public static javax.swing.JTextArea TxtAreaEstados;
    public static javax.swing.JTextArea TxtAreaReglas;
    private javax.swing.JTextField TxtCadena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
